// src/types/index.ts

export type ApplicationStatus = 'pending' | 'approved' | 'rejected';

export interface BusinessApplication {
  id?: string;
  ownerUid: string;
  ownerName: string;
  email: string;
  mobileNumber: string;
  
  businessName: string;
  category: string;
  customCategory?: string;
  description: string;
  
  address: {
    city: string;
    state: string;
    pinCode: string;
    googleMapsLink?: string;
  };
  
  contact: {
    primaryPhone: string;
    secondaryPhone?: string;
    whatsappNumber: string;
    businessEmail: string;
    website?: string;
    socialLinks: {
      facebook?: string;
      instagram?: string;
      youtube?: string;
      linkedin?: string;
    };
  };
  
  openingHours: string;
  logoUrl?: string;
  photoUrls: string[];
  
  status: ApplicationStatus;
  rejectionReason?: string;
  
  submittedAt: Date | string;
  
  // Generated by Admin after approval
  slug?: string; 
  publicUrl?: string;
}